"""
Motivational quotes and study tips for the sidebar.
"""

MOTIVATIONAL_QUOTES = [
    "The expert in anything was once a beginner.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The only way to do great work is to love what you do.",
    "Your limitation—it's only your imagination.",
    "Great things never come from comfort zones.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Success doesn't just find you. You have to go out and get it.",
    "Great results require great ambition.",
    "I will do my best and leave the rest to fate.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Be the change you wish to see in the world.",
    "Difficulties are just things to overcome, after all.",
    "You don't have to be great to start, but you have to start to be great.",
    "The future depends on what you do today.",
    "Make your life a masterpiece; imagine no limitations on what you can be.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "You're capable of amazing things.",
    "Step up and shine!",
    "All progress takes place outside the comfort zone.",
    "Don't go through life, grow through life.",
]

STUDY_TIPS = [
    "🎯 Break assignments into smaller tasks to avoid overwhelm.",
    "📅 Use the calendar view to plan your week ahead.",
    "⏱️ Try the Pomodoro Technique: 25 min work, 5 min break.",
    "📝 Mark assignments complete to stay motivated!",
    "🎨 Use course colors to organize and prioritize.",
    "⏰ Set reminders for assignments due today.",
    "📊 Check your dashboard daily for quick stats.",
    "🚀 Tackle high priority items first.",
    "💪 Celebrate completed assignments - you earned it!",
    "📚 Group assignments by course for better focus.",
    "🔔 Check overdue assignments and handle them ASAP.",
    "📈 Track your completion percentage weekly.",
    "🧠 Study when you're most productive, not when you think you should.",
    "🎪 Take regular breaks to stay fresh and focused.",
    "📱 Use your phone to check Trax on the go.",
    "✅ Create a routine: plan daily, track weekly.",
    "🎯 Set realistic deadlines before the actual due date.",
    "🌟 One small step each day leads to big results.",
    "📖 Read your assignment details carefully before starting.",
    "🤝 Don't hesitate to ask for help when needed.",
]
