# Generated by Django 5.1.2 on 2025-10-15 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='e.g., CS101, MATH201', max_length=20)),
                ('course_name', models.CharField(help_text='e.g., Introduction to Programming', max_length=200)),
                ('professor', models.CharField(blank=True, max_length=100)),
                ('credits', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('semester', models.CharField(blank=True, help_text='e.g., Fall 2025', max_length=50)),
                ('color', models.CharField(choices=[('#00274c', 'Navy'), ('#CC0000', 'Red'), ('#0077b6', 'Blue'), ('#2a9d8f', 'Teal'), ('#e76f51', 'Orange'), ('#9b59b6', 'Purple'), ('#16a085', 'Green'), ('#e74c3c', 'Crimson')], default='#00274c', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_code'],
                'unique_together': {('course_code', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.course'),
        ),
    ]
