# Generated by Django 5.1.2 on 2025-11-08 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_course_alter_assignment_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(help_text='Topic or subject of the podcast', max_length=300)),
                ('notes_text', models.TextField(help_text='Notes or content to turn into a podcast')),
                ('script', models.TextField(blank=True, help_text='AI-generated podcast script')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='podcasts/audio/')),
                ('tone', models.CharField(choices=[('casual', 'Casual & Fun'), ('professional', 'Professional'), ('educational', 'Educational'), ('motivational', 'Motivational')], default='educational', max_length=20)),
                ('length', models.CharField(choices=[('short', 'Short (5-10 min)'), ('medium', 'Medium (10-20 min)'), ('long', 'Long (20+ min)')], default='medium', max_length=20)),
                ('is_generated', models.BooleanField(default=False, help_text='Whether the podcast has been generated')),
                ('is_audio_generated', models.BooleanField(default=False, help_text='Whether audio has been generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='assignments.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
