# Generated by Django 5.1.2 on 2025-11-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='notes_file',
            field=models.FileField(blank=True, help_text='Upload a document (PDF, TXT, DOCX) as notes', null=True, upload_to='podcasts/notes/'),
        ),
    ]
