# Generated by Django 5.1.2 on 2025-11-08 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_podcast_notes_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Topic to generate notes about', max_length=300)),
                ('content', models.TextField(blank=True, help_text='AI-generated study notes')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic (Overview)'), ('intermediate', 'Intermediate (Standard)'), ('advanced', 'Advanced (Deep Dive)')], default='intermediate', max_length=20)),
                ('is_generated', models.BooleanField(default=False, help_text='Whether the notes have been generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_notes', to='assignments.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
