# Generated by Django 5.1.2 on 2025-11-08 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_studynotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('test', 'Test/Exam'), ('quiz', 'Quiz'), ('presentation', 'Presentation'), ('project_deadline', 'Project Deadline'), ('office_hours', 'Office Hours'), ('study_session', 'Study Session'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='e.g., Room 101, Online, Library', max_length=200)),
                ('color', models.CharField(default='#3b82f6', help_text='Color for calendar display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assignments.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reminder_type', models.CharField(choices=[('event', 'Event Reminder'), ('assignment', 'Assignment Due'), ('custom', 'Custom Reminder')], default='custom', max_length=20)),
                ('reminder_date', models.DateTimeField(help_text='When to be reminded')),
                ('notification_type', models.CharField(choices=[('none', 'No Notification'), ('in_app', 'In-App Only'), ('email', 'Email'), ('both', 'In-App & Email')], default='in_app', max_length=10)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether reminder has been acknowledged')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether notification has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='assignments.assignment')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='assignments.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_date'],
            },
        ),
    ]
